### ISSUE TITLE
head

### ISSUE THREAD

**Issue by goodmind** [types/npm-ramda#129]
I have this error

```ts
(1000,41): error TS2536: Type '0' cannot be used to index type 'T'.
```

line 1000 is
```ts
head<T extends List<any>>(list: T): T[0];
```

why this is don't working?

**Comment by tycho01** [comment]
Let me see. Would you perhaps have info for me on what TypeScript version you're running?

**Comment by goodmind** [comment]
2.1.5

**Comment by tycho01** [comment]
I managed to reproduce this in 2.2 locally, though not in Playground (2.1.4), so this seems like a regression that originated around TypeScript 2.1.5.
Thank you for bringing this up. I made a commit to address this as a temporary workaround, ditching the `[0]` approach until there is a working way of array access compatible with tuples again.

**Comment by goodmind** [comment]
@tycho01 it seems that it is fixed now by https://github.com/Microsoft/TypeScript/pull/13523 can you test it?

**Comment by tycho01** [comment]
Tried to pull the nightly but code didn't appear to have it yet. Still quite some things that puzzle me as well. That said, Andrej added regressions tests as well, looks pretty good. I presume the current nightly should still actually be good; did push a commit for that now.

**Comment by Willmo36** [comment]
I'm still having this issue when building with TypeScript@2.2.0. 

I'm getting the types via `yarn add -D types/npm-ramda` to in an attempt to avoid the `Nested<T>` issue with `evolve` in the current. `@types/ramda` version.

**Comment by tycho01** [comment]
Hi @Willmo36,
Sorry for the late response. I just managed to confirm the current version (`2.2.1-insiders.20170209`) as having addressed this.
Would you mind elaborating on your Nested/evolve issue? Feel free to submit a PR with a test reproducing it so we can permanently test against your use-case.

**Comment by Willmo36** [comment]
Sure thing.

`"@types/ramda": "^0.0.3"`
`"typescript": "2.2.0"`

```
function ramdaIssue(state: FormState): FormState {
    return R.evolve({
        index: R.inc
    }, state);
}
```

webpack using `awesome-typescript-loader`.
```
ERROR in [at-loader] src/components/actionForm/ActionForm.tsx:121:5
    Type 'Nested<FormState>' is not assignable to type 'FormState'.
  Property 'index' is missing in type 'Nested<FormState>'.ERROR in [at-loader] src/components/actionForm/ActionForm.tsx:121:5
    Type 'Nested<FormState>' is not assignable to type 'FormState'.
  Property 'index' is missing in type 'Nested<FormState>'.
```

However `R.assoc("index", state.index + 1, state)` will work fine, which is what I ended up doing. 

I searched the previous issues and found this; https://github.com/types/npm-ramda/issues/65. So the change as a result of that issue was in this repo but not the definitelytyped repo (or where ever `yarn add -d @types/ramda` comes from).

So I started using the `ramda.d.ts` from this repo instead of `@types/ramda` by doing `yarn add -D types/npm-ramda` but that I started getting the head problem that this thread is about.

TL-DR;
`yarn add -D @types/ramda` has this issue https://github.com/types/npm-ramda/issues/65
`yarn add -D types/npm-ramda` has this `head` issue

Hope this is enough info :)

**Comment by tycho01** [comment]
Added test:
```
  type FormState = { index: number };
  function ramdaIssue(state: FormState): FormState {
    return R.evolve({
        index: R.inc
    }, state);
  }
```

Inferred function type I'm seeing:
```
(local function) ramdaIssue(state: {
    index: number;
}): {
    index: number;
}
```

That's current master branch, TS version referenced in `package.json` (current nightly).
If you use VS Code, I think the settings folder checked in to version control should ensure the IDE would use the local TS version.
Is that something you might be able to reproduce using that?
